name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Install cargo-deny
        run: cargo install --locked cargo-deny
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Deny
        run: cargo deny check --show-stats
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        run: cargo audit
