name: Rust CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install cargo-audit
              run: cargo install cargo-audit
            - name: Install cargo-deny
              run: cargo install --locked cargo-deny
            - name: Build
              run: RUSTFLAGS='--cfg getrandom_backend="wasm_js"' cargo build -p salvo-worker --features "full" --target wasm32-unknown-unknown --verbose
            - name: Test
              run: cargo test --all --verbose
            - name: Deny
              run: RUSTFLAGS='--cfg getrandom_backend="wasm_js"' cargo deny check --show-stats
            - name: Clippy
              run: cargo clippy --all --features "full" --verbose -- -D warnings
            - name: Audit
              run: cargo audit
            - name: BuildExample
              run: cd examples/template && cargo install -q worker-build && RUSTFLAGS='--cfg getrandom_backend="wasm_js"' worker-build --release
